In [1]:
# Importing Required Libraries

import numpy as np
import pandas as pd
import warnings

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE,ADASYN
from imblearn.under_sampling import NearMiss

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVR, SVR, LinearSVC, SVC

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',None)

In [2]:
df = pd.read_csv(r'C:\Users\pc\OneDrive\Desktop\ML-Learning-Journey\Datasets\train.csv')
df

,ID,Loan Amount,Funded Amount,Funded Amount Investor,Term,Batch Enrolled,Interest Rate,Grade,Sub Grade,Employment Duration,Home Ownership,Verification Status,Payment Plan,Loan Title,Debit to Income,Delinquency - two years,Inquires - six months,Open Account,Public Record,Revolving Balance,Revolving Utilities,Total Accounts,Initial List Status,Total Received Interest,Total Received Late Fee,Recoveries,Collection Recovery Fee,Collection 12 months Medical,Application Type,Last week Pay,Accounts Delinquent,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
0,65087372,10000,32236,12329.36286,59,BAT2522922,11.135007,B,C4,MORTGAGE,176346.62670,Not Verified,n,Debt Consolidation,16.284758,1,0,13,0,24246,74.932551,7,w,2929.646315,0.102055,2.498291,0.793724,0,INDIVIDUAL,49,0,31,311301,6619,0
1,1450153,3609,11940,12191.99692,59,BAT1586599,12.237563,C,D3,RENT,39833.92100,Source Verified,n,Debt consolidation,15.412409,0,0,12,0,812,78.297186,13,f,772.769385,0.036181,2.377215,0.974821,0,INDIVIDUAL,109,0,53,182610,20885,0
2,1969101,28276,9311,21603.22455,59,BAT2136391,12.545884,F,D4,MORTGAGE,91506.69105,Source Verified,n,Debt Consolidation,28.137619,0,0,14,0,1843,2.073040,20,w,863.324396,18.778660,4.316277,1.020075,0,INDIVIDUAL,66,0,34,89801,26155,0
3,6651430,11170,6954,17877.15585,59,BAT2428731,16.731201,C,C3,MORTGAGE,108286.57590,Source Verified,n,Debt consolidation,18.043730,1,0,7,0,13819,67.467951,12,w,288.173196,0.044131,0.107020,0.749971,0,INDIVIDUAL,39,0,40,9189,60214,0
4,14354669,16890,13226,13539.92667,59,BAT5341619,15.008300,C,D4,MORTGAGE,44234.82545,Source Verified,n,Credit card refinancing,17.209886,1,3,13,1,1544,85.250761,22,w,129.239553,19.306646,1294.818751,0.368953,0,INDIVIDUAL,18,0,430,126029,22579,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67458,16164945,13601,6848,13175.28583,59,BAT3193689,9.408858,C,A4,MORTGAGE,83961.15003,Verified,n,Credit card refinancing,28.105127,1,0,13,0,4112,97.779389,19,w,1978.945960,0.023478,564.614852,0.865230,0,INDIVIDUAL,69,0,48,181775,34301,1
67459,35182714,8323,11046,15637.46301,59,BAT1780517,9.972104,C,B3,RENT,65491.12817,Source Verified,n,Credit card refinancing,17.694279,0,0,12,0,9737,15.690703,14,w,3100.803125,0.027095,2.015494,1.403368,0,INDIVIDUAL,14,0,37,22692,8714,0
67460,16435904,15897,32921,12329.45775,59,BAT1761981,19.650943,A,F3,MORTGAGE,34813.96985,Verified,n,Lending loan,10.295774,0,0,7,1,2195,1.500090,9,w,2691.995532,0.028212,5.673092,1.607093,0,INDIVIDUAL,137,0,17,176857,42330,0
67461,5300325,16567,4975,21353.68465,59,BAT2333412,13.169095,D,E3,OWN,96938.83564,Not Verified,n,Debt consolidation,7.614624,0,0,14,0,1172,68.481882,15,f,3659.334202,0.074508,1.157454,0.207608,0,INDIVIDUAL,73,0,61,361339,39075,0
67462,65443173,15353,29875,14207.44860,59,BAT1930365,16.034631,B,D1,MORTGAGE,105123.15580,Verified,n,Debt consolidation,16.052112,0,0,30,0,8762,81.692328,16,f,1324.255922,0.000671,1.856480,0.366386,0,INDIVIDUAL,54,0,47,196960,66060,0

In [3]:
df.shape

(67463, 35)

In [4]:
# Check null values
df.isnull().sum()

ID                              0
Loan Amount                     0
Funded Amount                   0
Funded Amount Investor          0
Term                            0
Batch Enrolled                  0
Interest Rate                   0
Grade                           0
Sub Grade                       0
Employment Duration             0
Home Ownership                  0
Verification Status             0
Payment Plan                    0
Loan Title                      0
Debit to Income                 0
Delinquency - two years         0
Inquires - six months           0
Open Account                    0
Public Record                   0
Revolving Balance               0
Revolving Utilities             0
Total Accounts                  0
Initial List Status             0
Total Received Interest         0
Total Received Late Fee         0
Recoveries                      0
Collection Recovery Fee         0
Collection 12 months Medical    0
Application Type                0
Last week Pay                   0
Accounts Delinquent             0
Total Collection Amount         0
Total Current Balance           0
Total Revolving Credit Limit    0
Loan Status                     0
dtype: int64

In [5]:
# Check duplicated rows
df.duplicated().sum()

0

In [6]:
# Selecting categorical and numerical features
categorical_feature = df.select_dtypes('object')
numerical_feature = df.select_dtypes('number')

In [7]:
# Encoding categorical features using LabelEncoder
labelencoder = LabelEncoder()

for i in categorical_feature.columns:
    df[i] = labelencoder.fit_transform(df[i])

In [8]:
# Splitting Features and Target Variable
X = df.drop('Loan Status', axis = 1)
y = df['Loan Status']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [10]:
# Standardize the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test =  scaler.transform(X_test)

In [11]:
pca = PCA(n_components = 2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
print(pca.explained_variance_ratio_)

[0.03829347 0.03517581]

In [12]:
# Check the class distribution before resampling
print("Class distribution before SMOTE (training set):")
print(y_train.value_counts())
print('-' * 35)

# Apply SMOTE for balancing the dataset on the training set
sm = SMOTE(sampling_strategy='minority', random_state=42, n_jobs=1)
X_train, y_train = sm.fit_resample(X_train, y_train)

# Check the class distribution after resampling
print("Class distribution after SMOTE (training set):")
print(y_train.value_counts())
print('-' * 35)

# Optional: Check the class distribution in the test set
print("Class distribution in test set:")
print(y_test.value_counts())
print('-' * 35)

Class distribution before SMOTE (training set):
Loan Status
0    48947
1     5023
Name: count, dtype: int64
-----------------------------------
Class distribution after SMOTE (training set):
Loan Status
0    48947
1    48947
Name: count, dtype: int64
-----------------------------------
Class distribution in test set:
Loan Status
0    12275
1     1218
Name: count, dtype: int64
-----------------------------------

### **Model Training and Evaluation**

In this section, we initialize several machine learning models, including:
- *Logistic Regression*
- *Decision Tree Classifier*
- *Random Forest Classifier*
- *K-Nearest Neighbors (KNN) Classifier*
- *Support Vector Classifier (SVC)*

For each model:
1. The model is trained on the training dataset.
2. Predictions are made on the test dataset.
3. The accuracy score is calculated for each model, allowing us to compare their performance.

**This gives us an idea of which model performs best on our dataset based on the accuracy score.**

In [13]:
models = {
    'Logistic' : LogisticRegression(),
    'Decision' : DecisionTreeClassifier(),
    'Random Forest' : RandomForestClassifier(),
    'KNN' : KNeighborsClassifier(),
    'SVC' : SVC()
}

for i, k in models.items():
    k.fit(X_train, y_train)
    y_pred = k.predict(X_test)
    Score = accuracy_score(y_test, y_pred)
    print(f'{i} : {Score}')

Logistic : 0.5190839694656488
Decision : 0.6768694878826058
Random Forest : 0.7037723263914623
KNN : 0.6404061365152302
SVC : 0.5264211072407915